spring.application.name=TaskBoard
spring.r2dbc.url=r2dbc:postgresql://localhost:5432/taskboard
spring.r2dbc.username=taskboard
spring.r2dbc.password=password

spring.flyway.url=jdbc:postgresql://localhost:5432/taskboard
spring.flyway.user=taskboard
spring.flyway.password=password